extends: airbnb-base

parser: babel-eslint

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  jest: true
  node: true

plugins:
  - jest

parserOptions:
  ecmaVersion: 2018

# https://eslint.org/docs/rules
rules:
  default-case: 0
  # We disable the ESLint check for LF EOLs and enforce it via .gitattributes
  # https://github.com/filerjs/filer/issues/403#issuecomment-422503251
  linebreak-style: 0
  # Because it collides with Flow props' type definitions
  lines-between-class-members: 0
  # Because it collides with Flow "munge_underscores" option
  no-underscore-dangle: 0
  quotes: [error, single, { allowTemplateLiterals: true }]
  semi: [error, never]
  # https://github.com/babel/babel-eslint#setup
  strict: 0

  # Disable the dev dependencies check
  # https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md
  "import/no-extraneous-dependencies": 0

  # https://github.com/jest-community/eslint-plugin-jest#rules
  "jest/consistent-test-it": error
  "jest/expect-expect": error
  "jest/no-alias-methods": error
  "jest/no-disabled-tests": error
  "jest/no-focused-tests": error
  "jest/no-identical-title": error
  "jest/no-jest-import": error
  "jest/no-test-callback": error
  "jest/no-test-prefixes": error
  "jest/no-test-return-statement": error
  "jest/prefer-strict-equal": error
  "jest/prefer-to-be-null": error
  "jest/prefer-to-be-undefined": error
  "jest/prefer-to-contain": error
  "jest/prefer-to-have-length": error
  "jest/require-tothrow-message": error
  "jest/valid-describe": error
  "jest/valid-expect": error
