language: node_js

node_js:
  - "10"

os:
  - linux
  - osx
  # - windows

cache:
  npm: true
  directories:
    - node_modules

script:
  - npm test
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      bash scripts/ci/test_coverage.sh
    fi
